language: python
python:
  - "2.7"

install:
  - pip install tox

script:
  - mv "${TRAVIS_BUILD_DIR}" "${TRAVIS_BUILD_DIR%/*}/buildbotcustom" || true
  - tox

# currently cannot customise per user fork, see:
# https://github.com/travis-ci/travis-ci/issues/1094
# notifications:
#   irc: "irc.mozilla.org#releng"
#   on_success: always
#   on_failure: always
